#!/bin/sh

# INTERFACE="$1"
# TTY="$2"		# "" for xl2tp
# SPEED="$3"		# 0 for xl2tp
# LOCAL_IP="$4"
# REMOTE_IP="$5"
# IPOPT="$6"		# options file should set it to xl2tpd lac name

# env:
#  IFNAME=ppp0
#  DNS1=8.8.8.8
#  DNS2=8.8.8.8
#  IPLOCAL=192.168.1.1
#  IPREMOTE=192.168.1.2
#  LLLOCAL=fe80::300e:4230:c8ee:62d5
#  LLREMOTE=fe80::f99b:dd07:7567:4453
#  USEPEERDNS=1
#  PPPD_PID=123
#  PEERNAME=abc		# if authenticated

rm -f "/run/ifname-$IFNAME"
if [ -f /etc/ppp/devnameprefix ] && read prefix notused < /etc/ppp/devnameprefix && [ -n "$prefix" -a -n "$PEERNAME" ]
then
  oldname="$IFNAME"
  newname="$prefix$PEERNAME"
  if ip link set "$oldname" name "$newname"	# try to rename while UP
  then
    IFNAME="$newname"
  else
    ip link set "$oldname" down
    ip link set "$oldname" name "$newname" && IFNAME="$newname"
    ip link set "$IFNAME" up
  fi
fi
export IFNAME
echo "$IFNAME" > "/run/ifname-$oldname"

[ -n "$6" ] && echo "$IFNAME" > "/run/lac-$6"

cat /etc/ppp/networks \
| cut -f1 -d'#' \
| while read peer subnet rest
do
  [ -z "$peer" -o -z "$subnet" ] && continue
  [ "$peer" != "$PEERNAME" ] && continue
  ip route add "$subnet" via "$IPREMOTE" dev "$IFNAME"
done

[ -x /etc/ppp/ip-up.local ] && /etc/ppp/ip-up.local "$IFNAME" "$2" "$3" "$4" "$5" "$6"
